// <auto-generated />
using System;
using FinanceTracker.Services.Budget.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.Services.Budget.Data.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260318084020_InitialCreateBudgetTables")]
    partial class InitialCreateBudgetTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Infrastructure.Entities.Budget.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("bc03e7d4-153f-4328-bd21-95707d1a2d09"))
                        .HasColumnName("id");

                    b.Property<double>("ActualBudget")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_budget");

                    b.Property<int>("AlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(80)
                        .HasColumnName("alert_threshold");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("TargetItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_items");

                    b.Property<double>("TargetSavings")
                        .HasColumnType("double precision")
                        .HasColumnName("target_savings");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_budget_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_budget_created_at");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_budget_due_date");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_budget_group_id");

                    b.HasIndex("GroupId", "IsDeleted", "IsActive")
                        .HasDatabaseName("ix_budget_group_active");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Infrastructure.Entities.Budget.BudgetMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_budget_members_budget_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_budget_members_user_id");

                    b.ToTable("budget_members", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
